package net.auio.recruitworking.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Info {
    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   权限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.perm
     *
     * @mbg.generated
     */
    private String perm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.username
     *
     * @return the value of info.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.username
     *
     * @param username the value for info.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.password
     *
     * @return the value of info.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.password
     *
     * @param password the value for info.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.perm
     *
     * @return the value of info.perm
     *
     * @mbg.generated
     */
    public String getPerm() {
        return perm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.perm
     *
     * @param perm the value for info.perm
     *
     * @mbg.generated
     */
    public void setPerm(String perm) {
        this.perm = perm == null ? null : perm.trim();
    }
}